## 矩阵所表示的行列问题

In [14]:
import numpy as np
a = np.array([[1],[2]]) #两行一列，也就是一个列向量
a1 = np.array([[1,2],[3,4]]) #2*2 一个对应一行
b = np.array([1,2]) # 行数=2，即是一列向量，列数不存在 其实是一“列”

c = np.array([[3,2]]) #一行两列，即一个行向量
d = np.array([[[1,2]]]) #三维，“高度”为2
print(a.shape,'\n',a1, '\n', a1.shape,
      b.shape, c.shape, d.shape, )

(2, 1) 
 [[1 2]
 [3 4]] 
 (2, 2) (2,) (1, 2) (1, 1, 2)


## 矩阵拼接

In [15]:
import numpy as np
aa = np.array([[[1,2,3],[4,5,6]],[[2,2,3],[4,5,6]],[[3,2,3],[4,5,6]]])
a = np.array([[4,2,3],[4,5,6]])
print(aa.shape, a.shape)
data = np.append(aa,a)#先拼接成一个行向量
print(data)
dim = aa.shape#获取原矩阵的维数
print('原矩阵维数：',dim)
data1 = data.reshape(dim[0]+1,dim[1],dim[2])#再通过原矩阵的维数重新组合
print('合并矩阵：\n',data1)
print('维数：',data1.shape)

(3, 2, 3) (2, 3)
[1 2 3 4 5 6 2 2 3 4 5 6 3 2 3 4 5 6 4 2 3 4 5 6]
原矩阵维数： (3, 2, 3)
合并矩阵：
 [[[1 2 3]
  [4 5 6]]

 [[2 2 3]
  [4 5 6]]

 [[3 2 3]
  [4 5 6]]

 [[4 2 3]
  [4 5 6]]]
维数： (4, 2, 3)
